develop login-page navbar, enhanced the avartar and addressed issue #10
KMF-js/Veritas-E-Portal pull request #13
Opened 2023-03-27 11:33 UTC by Wence17

close #11 #12

2023-03-27 16:34 UTC, KMF21 commented
No screenshots? please provide screenshots.
Also, your PR should have a distinct title name and then your descriptions should come up in the body and not the title.
@Wence17 
well-done. cheers!

2023-03-27 16:40 UTC, KMF21 requested changes

2023-03-27 16:40 UTC, KMF21 commented on app/error/page.tsx
> +      <NavbarRow />
why is this still being called NavbarRow?

2023-03-27 16:40 UTC, KMF21 commented on components/NavbarLogin.tsx
> +                <div className='flex mx-12 items-center justify-center pb-0 mt-0'>
why flex and not flex-1?

2023-03-28 23:36 UTC, Wence17 commented on components/NavbarLogin.tsx
> +                <div className='flex mx-12 items-center justify-center pb-0 mt-0'>
@KMF21 That's the middle navbar component. If I should flex-1, then it will be aligned to the left more.

2023-03-28 23:43 UTC, closed without merging