develop error page and enhance nav bar
KMF-js/Veritas-E-Portal pull request #6
Opened 2023-03-24 02:43 UTC by Wence17

![image](https://user-images.githubusercontent.com/93437186/227410351-cd5dc0e6-1c7a-45c2-bca2-914314093123.png)

I enhanced the navbar responsiveness.

![image](https://user-images.githubusercontent.com/93437186/227410473-839e5d63-a0c0-4796-9fe5-e329591b8435.png)

Yet to understand nextjs rendering so I have to alter the code to do the rendering.  But I set it to the default after testing my code.

2023-03-24 09:36 UTC, KMF21 commented on app/components/Navbar.tsx
> -    <div className="bg-white h-[50px] flex items-center justify-center ">
lets make the height (10px  mobile)(30px medium)(50px large)

2023-03-24 09:43 UTC, KMF21 requested changes

2023-03-24 09:50 UTC, KMF21 commented
well-done @Wence17

take note of this
![errorw](https://user-images.githubusercontent.com/63710324/227486879-9cee10e7-e2c7-4172-b5cd-d26528e53d6f.png)
cheers!!

2023-03-24 18:53 UTC, Wence17 commented on app/components/Navbar.tsx
> -    <div className="bg-white h-[50px] flex items-center justify-center ">
This is not my last push

2023-03-24 18:54 UTC, Wence17 commented on app/components/Navbar.tsx
> -    <div className="bg-white h-[50px] flex items-center justify-center ">
![image](https://user-images.githubusercontent.com/93437186/227614535-4859f434-b9e9-4875-a137-f09ad46aae04.png)




check this out.  Defined my screen sizes for the container class or it's not necessary?

2023-03-24 19:27 UTC, Wence17 commented on app/page.tsx
> +import ErrorPage from './ErrorPage'
Alright!

done

2023-03-24 19:59 UTC, Wence17 commented on app/components/ErrorsCodes/Error404.tsx
![image](https://user-images.githubusercontent.com/93437186/227624157-30e68d47-a8b6-4c23-a30b-436a614e4dd7.png)



check out this documentary.
https://nextjs.org/learn/seo/crawling-and-indexing/status-codes



also see this stackoverflow questions
https://stackoverflow.com/questions/70712833/nextjs-custom-error-page-with-correct-status-code
https://stackoverflow.com/questions/74991106/how-to-handle-status-codes-at-the-middleware-level

2023-03-24 20:05 UTC, Wence17 commented on app/components/Navbar.tsx
> -    <div className="bg-white h-[50px] flex items-center justify-center ">
I did not add this to the new push, just a suggestion.

2023-03-26 20:54 UTC, KMF21 approved these changes

2023-03-26 20:54 UTC, merged